CategoryCard Component for Landing-Bubbles + Tagline Links
Americastestkitchen/mise-ui pull request #383
Opened 2021-03-29 13:24 UTC by jbonAA

2021-03-29 13:34 UTC, jaslakson requested changes
This looks great overall - a couple of small requests - also, please double check the linter output. We usually only indent 2 spaces and I see lots of 4 in here. There's also a few other spacing issues around if/else, etc.

2021-03-29 13:34 UTC, jaslakson commented on src/components/Cards/CategoryCard/CategoryCard.stories.js
> +        assetType={'svgIcon'}
For string prop values we usually pass as double quotes - `assetType="svgIcon"`.

2021-03-29 13:34 UTC, jaslakson commented on src/components/Cards/CategoryCard/index.js
> +            background-color: #ffffff;
even though this is just white, we typically refer to the colors using the variable name instead of the hex code.

2021-03-29 13:34 UTC, jaslakson commented on src/components/Cards/CategoryCard/index.js
> +    ${props => props.iconId === 'shoppingCart' && css`
could we add a className to the shopping card svg and then have a scoped css rule here using that class name instead of the props function?

2021-03-29 13:34 UTC, jaslakson commented on src/components/DesignTokens/Icon/svgs/ShoppingCart.js
> +        <g id="noun_Shopping_Cart_179069" transform="translate(-.6 -.3)">
let's drop all of these `id` attributes - same for the auto generated `className` attrs such as `cls-1`

2021-03-29 13:34 UTC, jaslakson commented on src/components/DesignTokens/Icon/svgs/TrendingArrow.js
> +            data-name="Path 36217"
drop this attribute

2021-03-29 13:57 UTC, ttornese commented on src/components/Cards/CategoryCard/__test__/CategoryCard.spec.js
> +                assetType={'productImage'}
similar to jason's comment about these props can all be passed as with `"` and no `{`

2021-03-29 14:03 UTC, ttornese commented on src/components/Cards/CategoryCard/iconMap.js
> +    'shoppingCart': <ShoppingCart fill={color.mint}/>,
with this syntax `(<ShoppingCart ... />)` the render functions for all of these icons will run every time this `IconMap` is called. i would try rewriting the map to look something like this:

```
const IconMap = {
  shoppingCart: ShoppingCart,
  ...
};
```

then inside the component that imports `IconMap`:

```
  const CategoryIcon = IconMap[svgId];
  ...
  return (
    <CategoryIcon fill={color.mint} />
  );
```

2021-03-29 14:04 UTC, ttornese commented on src/components/Cards/CategoryCard/iconMap.js
> +    'shoppingCart': <ShoppingCart fill={color.mint}/>,
it looks like the fill prop is the same color for every icon in the map so you probably don't need to include that in the map. it can be a dynamic prop passed to the `CategoryCard` or just hard coded in `CategoryCard`

2021-03-29 14:12 UTC, ttornese commented on src/components/DesignTokens/Icon/svgs/ShoppingCart.js
> +        xmlns="http://www.w3.org/2000/svg"
these icons will be for display only. they dont add any extra context or functionality to the component. so for accessibility reasons they need should be hidden from screen readers and the tab index. you can add these attributes to the SVGs to make them a bit more accessible:

```
aria-hidden="true" // hide from screen reader
focusable="false" // remove from tab order
role="img" // given to svgs that act as images
```

2021-03-29 14:23 UTC, jbonAA commented on src/components/Cards/CategoryCard/CategoryCard.stories.js
> +        assetType={'svgIcon'}
assetType="svgIcon"

2021-03-29 14:24 UTC, jbonAA commented on src/components/Cards/CategoryCard/index.js
> +            background-color: #ffffff;
box-shadow: 0 3px 6px 0 ${color.white};

2021-03-29 14:25 UTC, jbonAA commented on src/components/Cards/CategoryCard/index.js
> +            background-color: #ffffff;
background-color: ${color.white};

2021-03-29 14:30 UTC, jbonAA commented on src/components/Cards/CategoryCard/__test__/CategoryCard.spec.js
> +                assetType={'productImage'}
assetType="productImage"

2021-03-29 14:39 UTC, jbonAA commented on src/components/Cards/CategoryCard/iconMap.js
> +    'shoppingCart': <ShoppingCart fill={color.mint}/>,
Nice catch!

2021-03-29 14:44 UTC, jbonAA commented on src/components/Cards/CategoryCard/index.js
> +    ${props => props.iconId === 'shoppingCart' && css`
.shopping-cart-icon {
    position: absolute;
    left: 18%;
  }

2021-03-29 14:45 UTC, mirdathebirda commented on src/components/Cards/CategoryCard/index.js
> +    };
you can move this logic to line 81 and use a ternary and drop displayImage variable

2021-03-29 14:45 UTC, mirdathebirda commented on src/components/Cards/CategoryCard/index.js
> +    svgId: PropTypes.oneOf(['shoppingCart', 'star', 'trendingArrow', 'play', '']),
since these values aren't required, don't forget to add in some default props for them

2021-03-29 14:51 UTC, jbonAA commented on src/components/Cards/CategoryCard/index.js
> +    };
```
const CategoryIcon = IconMap[svgId];

<ImageWrapper>
        {assetType === 'productImage' ? <Image className="category-product-image" imageAlt={tagline} imageUrl={cloudinaryId}/> : <CategoryIcon fill={color.mint} /> }
</ImageWrapper>
```

2021-03-29 14:56 UTC, mirdathebirda commented on src/components/DesignTokens/Icon/svgs/LandingPlay.js
> +        height="30"
it would be good to use `viewbox` attribute instead of an explicit width and height for the svgs. viewbox preserves the aspect ratio which comes in handy when scaling

2021-03-29 15:02 UTC, jbonAA commented on src/components/DesignTokens/Icon/svgs/LandingPlay.js
> +        height="30"
```
viewBox="0 0 30.001 30"
```

2021-03-29 18:26 UTC, jaslakson commented on src/components/Cards/CategoryCard/index.js
> +  const CategoryIcon = IconMap[svgId];
@jbonAA I think you need to have either 1) a fallback if `svgId` doesn't exist in `IconMap` or 2) check to see if `svgId` is in `IconMap` before rendering, opting for `null` if it doesn't exist.

2021-03-29 20:15 UTC, jbonAA commented on src/components/Cards/CategoryCard/index.js
> +  const CategoryIcon = IconMap[svgId];
Opted for a fallback icon in the instance where svgId does not exist in IconMap

```
const CategoryIcon = IconMap?.[svgId] || IconMap['star'];
```

2021-03-30 15:25 UTC, ttornese approved these changes

2021-03-30 15:30 UTC, jaslakson approved these changes
💯

2021-03-30 15:41 UTC, mirdathebirda approved these changes
🔥 🎆 💯

2021-03-30 16:05 UTC, merged