env: github-actions
Americastestkitchen/mise-ui pull request #558
Opened 2021-11-19 17:05 UTC by harry-atk

Needed for PR:
1. atkdeployer email verified
2. GH_TOKEN added to github secrets with repo and admin:org permissions
3. NPM_TOKEN added to github secrets with elevated permissions if 2fa exists

Mise-UI Improvements!
- react preset for v17 jsx format
- .editorconfig file for universal editor settings
- github actions
  - for pushes to remote branches run `yarn scripts validate` && `yarn scripts build`
  - for pushes to remote master run `yarn scripts release`
- interactive scripts for setup, validate, build, and release
  - setup: install recommended extensions if vscode's `code` command is on path
  - validate: run linter and test runner
  - build: clean dist, build babel and typescript, then copy package files
  - release: validate, build, and deploy
    - updates version of package.json and changelog
    - deploys new git tag and github release
    - deploys dist folder to npm
- vscode settings
  - recommended extensions, reveal in the extensions tab of vscode
  - default editor: runs desired formatter (may need to disable prettier locally for now)
  - format on save: runs formatter on save
- remove unused service worker file

2021-11-19 17:59 UTC, jaslakson requested changes
This looks awesome! can't wait to have it integrated. Let's add some additional comments and context for other devs. Very cool stuff!

2021-11-19 17:59 UTC, jaslakson commented on .vscode/extensions.json
> +    // "esbenp.prettier-vscode",
if this is commented out should we remove it? Is this something that you're still working on?

2021-11-19 17:59 UTC, jaslakson commented on package.json
> +  "version": "1.23.22",
Looks like this should just be `.21`

2021-11-19 17:59 UTC, jaslakson commented on scripts/_exec.js
> +
Let's add some comments to this file to describe what each task is doing and why it is doing it for future reference and for other devs.

2021-11-19 18:08 UTC, harry-atk commented on .vscode/extensions.json
> +    // "esbenp.prettier-vscode",
Let's remove it, the prettier formatter would be nice to have, but would affect a lot of the linter configuration. The Eslint formatter should be used for now.

2021-11-19 18:09 UTC, harry-atk commented on scripts/_exec.js
> +
👍

2021-11-19 18:17 UTC, harry-atk commented on package.json
> +  "version": "1.23.22",
auto shipit seems to have pushed 1.23.22 for those debugging updates yesterday. I put out the tag and release, but I think there might be issues since the version change isn't in that release. Let me see if on my local auto setup if labeling minor will resolve this

2021-11-22 16:29 UTC, harry-atk commented
because dist folder is linked and devDependencies is removed from those directories package dependencies, npm link commands seem to no longer be necessary. Removing those comments from readme.

2022-05-25 19:27 UTC, closed without merging