Text component with a background causes font styling issues
Americastestkitchen/mise-ui pull request #631
Opened 2022-02-15 14:27 UTC by kayseriatk

2022-02-15 15:22 UTC, harry-atk requested changes
bold text here is provided by barista text editors. These wrap text in <strong> and <em> for bold and italic. I would change the font type to bold in those tags and not on all text components

2022-02-17 15:14 UTC, harry-atk commented
We probably want pnb for only bold right? not just bold that is also italic?

2022-02-17 15:23 UTC, harry-atk approved these changes

2022-02-17 21:18 UTC, merged

2022-02-17 21:22 UTC, atk-dm commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v1.33.7`](https://github.com/Americastestkitchen/mise-ui/releases/tag/v1.33.7) :rocket: