Km content 115
Americastestkitchen/mise-ui pull request #665
Opened 2022-03-11 13:48 UTC by kayseriatk

2022-03-11 14:18 UTC, harry-atk requested changes
seems like tsc is failing. rotate is in svg props already, to add a boolean | undefined to a styled component props do

export const Svg = styled.svg\`
to
export const Svg = styled.svg<{rotated?: boolean}>\`
then update the name of the prop to  rotated to not conflict with the svg prop name

2022-03-14 16:18 UTC, harry-atk approved these changes

2022-03-14 19:00 UTC, harysvizcaino01 approved these changes

2022-03-15 15:42 UTC, merged

2022-03-15 15:58 UTC, atk-dm commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v1.33.11`](https://github.com/Americastestkitchen/mise-ui/releases/tag/v1.33.11) :rocket: