WIP CORE-480: atk homepage a11y screen reader fixes
Americastestkitchen/mise-ui pull request #781
Opened 2022-06-13 16:01 UTC by ttornese

2022-06-13 16:02 UTC, ttornese commented on src/components/Cards/ArticleCard/ArticleCard.tsx
> +      <CardBody>
Ordering was changed here so document information is read by a screen reader before the badge & favorite information.

2022-06-13 16:43 UTC, oddwili requested changes
small question

2022-06-13 16:43 UTC, oddwili commented on src/components/Cards/ArticleCard/ArticleCard.tsx
> +  order: 1;
If the template was updated to have this component first, is this line necessary?

2022-06-13 16:58 UTC, ttornese commented on src/components/Cards/ArticleCard/ArticleCard.tsx
> +  order: 1;
Yes, it's a bit of a strange case. I needed to re-order the template so the screen reader reads the `CardBody` component's content to a user first, before the content of the `Stack` component. I added the order style here because visually, the `CardBody` component needs to be displayed below the `Stack` component (mobile) or to the right (tablet and above).

2022-06-13 19:06 UTC, oddwili approved these changes

2022-06-13 19:22 UTC, merged

2022-06-21 19:47 UTC, atk-dm commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v1.33.24`](https://github.com/Americastestkitchen/mise-ui/releases/tag/v1.33.24) :rocket: