suggestion card tsx
Americastestkitchen/mise-ui pull request #804
Opened 2022-06-29 16:21 UTC by jwinnfeild2517

2022-07-12 00:35 UTC, oddwili requested changes

2022-07-12 00:35 UTC, oddwili commented on src/components/Cards/shared/UserAttributions/UserAttributions.tsx
> +  numRatings?: number | null;
if optional, could we just keep this to `number`?

2022-07-12 00:35 UTC, oddwili commented on src/components/DesignTokens/Icon/svgs/Save.tsx
> +    className={className}
if this is not passed in it will set `undefined` as the classname

2022-07-12 19:29 UTC, jwinnfeild2517 commented on src/components/Cards/shared/UserAttributions/UserAttributions.tsx
> +  numRatings?: number | null;
The current API response returns null when these values are not available.

2022-07-20 16:31 UTC, oddwili approved these changes

2022-07-20 16:54 UTC, merged