WEB-53: Card Image min-heights for flickity safari
Americastestkitchen/mise-ui pull request #831
Opened 2022-07-18 20:33 UTC by jbonAA

Issue where flickity on safari isn't correctly resizing uncached images on page load

- Tested on recipes/reviews/homepages

2022-07-18 20:48 UTC, harry-atk requested changes
Needs 162px height for standard cards outside of carousels below certain viewports. Search is okay because of SearchPage.scss, but theres pages in reviews/browse for example that are distorted below certain breakpoints.

2022-07-19 16:15 UTC, jbonAA commented
> Needs 162px height for standard cards outside of carousels below certain viewports. Search is okay because of SearchPage.scss, but theres pages in reviews/browse for example that are distorted below certain breakpoints.

Updated StandardSlide & Espresso portion of pr to handle standard card image heights only when they're within the context of a carousel

2022-07-19 16:37 UTC, harry-atk approved these changes

2022-07-19 16:37 UTC, harry-atk approved these changes

2022-08-17 16:33 UTC, merged

2022-08-17 16:38 UTC, atk-dm commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v1.33.34`](https://github.com/Americastestkitchen/mise-ui/releases/tag/v1.33.34) :rocket: