convert podcast episode card to typescript
Americastestkitchen/mise-ui pull request #864
Opened 2022-07-29 16:06 UTC by jwinnfeild2517

## what does this PR do

converts the podcast episode card to typescript

2022-08-02 21:43 UTC, oddwili requested changes

2022-08-02 21:43 UTC, oddwili commented on src/components/Cards/PodcastEpisodeCard/PodcastEpisodeCard.tsx
> +  /** episode id */
We can remove these comments. They're descriptive enough with the prop names and comments are hard to maintain

2022-08-02 21:43 UTC, oddwili commented on src/components/Cards/PodcastEpisodeCard/PodcastEpisodeCard.stories.tsx
> +        // eslint-disable-next-line no-console
does using `console.error` work for this? I know we need to surface the error, but I'd like to avoid using this eslint override if possible

2022-08-02 21:43 UTC, oddwili commented on src/components/Cards/PodcastEpisodeCard/PodcastEpisodeCard.stories.tsx
> +        // eslint-disable-next-line @typescript-eslint/no-unused-vars
if we're not using this variable anywhere, can we get rid of it? That way we don't have to use this eslint disable

2022-08-02 21:43 UTC, oddwili commented on src/components/Cards/PodcastEpisodeCard/PodcastEpisodeCard.stories.tsx
>  import { withKnobs, text, select } from '@storybook/addon-knobs';
@jbonAA left a similar comment on https://github.com/Americastestkitchen/mise-ui/pull/867 so I'm sharing this here:

> Roman left a good comment on one of my prs about @storybook/addon-knobs last week -
> 
> addon-knobs is deprecated. Args/controls provides the same functionality.
> 
> https://storybook.js.org/addons/@storybook/addon-knobs
https://github.com/storybookjs/storybook/discussions/15060
> 
> I think moving forward we want to utilize a pattern similar to: https://github.com/Americastestkitchen/mise-ui/blob/typescript-conversion/src/components/Ads/ShowcaseAds/FreeTrialAd/FreeTrialAd.stories.tsx
> 
> Can this stories file be updated to match above?

2022-08-03 18:46 UTC, jwinnfeild2517 commented on src/components/Cards/PodcastEpisodeCard/PodcastEpisodeCard.stories.tsx
> +        // eslint-disable-next-line no-console
removed

2022-08-03 18:46 UTC, jwinnfeild2517 commented on src/components/Cards/PodcastEpisodeCard/PodcastEpisodeCard.stories.tsx
> +        // eslint-disable-next-line @typescript-eslint/no-unused-vars
removed

2022-08-03 18:47 UTC, jwinnfeild2517 commented on src/components/Cards/PodcastEpisodeCard/PodcastEpisodeCard.stories.tsx
>  import { withKnobs, text, select } from '@storybook/addon-knobs';
updated to argtypes

2022-10-05 18:10 UTC, closed without merging