core-582: Issue loading TikTok videos on Firefox ATK, CIO, and CCO
Americastestkitchen/mise-ui pull request #897
Opened 2022-08-17 18:16 UTC by tdorin

# [CORE-582]([SHORTCUT_LINK](https://bostoncommonpress.atlassian.net/browse/CORE-582))

## What Does This Do?
Allows TikTok to re-render on refresh, and to render in all browsers. 

## To view the bug:
visit: https://mise-ui.netlify.app/?path=/story/components-mediaembed--tik-tok and refresh page, or simply select another story and return to the tiktok embed. iframe does not re-render.

### Author Tested
- [x] Chrome
- [ ] Edge
- [x] Firefox
- [x] Safari

2022-08-17 18:35 UTC, harry-atk reviewed
This looks like it adds script tags on every render now. And would do so for the other components that use useScript. Do we just need to wait until we're sure the component mounts before adding the script or is there something else going on?

2022-08-17 20:25 UTC, tdorin commented
> This looks like it adds script tags on every render now. And would do so for the other components that use useScript. Do we just need to wait until we're sure the component mounts before adding the script or is there something else going on?

Got it! Per our conversation, I made the update!

2022-08-17 21:45 UTC, oddwili approved these changes

2022-08-18 13:58 UTC, harry-atk requested changes

2022-08-18 13:58 UTC, harry-atk commented on src/components/MediaEmbed/utilities.ts
> -    if (!src) return () => {};
could we leave `if (!src) return () => {};` on useScript.

2022-08-18 13:58 UTC, harry-atk commented on src/components/MediaEmbed/utilities.ts
> +      .then(res => (res.ok ? res.json() : ''))
lets leave this back to undefined to match catch condition

2022-08-18 13:58 UTC, harry-atk commented on src/components/MediaEmbed/utilities.ts
> +        setData(payload.html);
should be `payload?.html` for the conditions that don't return a payload. If you want empty condition to be a string `payload?.html ?? ''`

2022-08-18 15:12 UTC, tdorin commented on src/components/MediaEmbed/utilities.ts
> +        setData(payload.html);
Good catch!!

2022-08-18 16:54 UTC, harry-atk approved these changes

2022-08-23 14:43 UTC, merged

2022-08-23 14:47 UTC, atk-dm commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v1.33.36`](https://github.com/Americastestkitchen/mise-ui/releases/tag/v1.33.36) :rocket: