WEB-598: HeroCard
Americastestkitchen/mise-ui pull request #952
Opened 2022-11-04 19:18 UTC by oddwili

[WEB-598](https://bostoncommonpress.atlassian.net/browse/WEB-598)

HeroCard without desktop styling finalized. I left in some TODOs to clean up later.

2022-11-07 21:21 UTC, tdorin requested changes
Just a few questions about props.

2022-11-07 21:21 UTC, tdorin commented on v2/src/components/blocks/HeroCard/HeroCard.tsx
> +          <h1 className={styles.headline}>Your Summer Needs These Three Tomato Sandwiches</h1>
Thinking that this h1 headline should probably be included in your props vs being hardcoded.

2022-11-07 21:21 UTC, tdorin commented on v2/src/components/blocks/HeroCard/styles/HeroCard.module.scss
> +    background-image: url('https://res.cloudinary.com/hksqkdlah/image/upload/SFS_Broiled_Chicken_with_Gravy_379_rx4dzb.jpg');
isn't the image passed as a prop?

2022-11-07 21:21 UTC, tdorin commented on v2/src/components/blocks/HeroCard/HeroCard.stories.tsx
> +HeroCardStory.args = {
Should probably include for a headline too.

2022-11-08 13:58 UTC, bradwaropay commented
Agreed to all @tdorin comments. I would make those props and just set a default.

2022-11-08 16:46 UTC, oddwili commented on v2/src/components/blocks/HeroCard/styles/HeroCard.module.scss
> +    background-image: url('https://res.cloudinary.com/hksqkdlah/image/upload/SFS_Broiled_Chicken_with_Gravy_379_rx4dzb.jpg');
oop, yes!

2022-11-08 22:14 UTC, merged