WEB-54: update standard card title font and proxima nova font-face
Americastestkitchen/mise-ui pull request #998
Opened 2023-10-13 22:53 UTC by oddwili

This also removes old comments to take out blocks after brand consolidation wrapped up.

2023-10-16 14:09 UTC, harry-atk commented on src/styles/typography.ts
>    pnr: 'proximaNovaRegular, sans-serif',
should be proxima-nova to match the change to font-face

2023-10-16 14:10 UTC, joshuabrileyatk commented on src/components/Cards/shared/Title/index.js
> +    font-weight: 700;
Not a deal breaker, but the font weight can also be included as part of the font shorthand line above. 
https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties#font_properties

2023-10-16 14:10 UTC, joshuabrileyatk approved these changes

2023-10-16 14:25 UTC, harry-atk commented on src/styles/typography.ts
>    pnr: 'proximaNovaRegular, sans-serif',
also a lot of pnb usage we need font weights for https://github.com/search?q=repo%3AAmericastestkitchen%2Fmise-ui+pnb&type=code

2023-10-17 12:22 UTC, joshuabrileyatk commented on src/components/Accordion/index.js
> +    font-weight: 700;
Line 42 seems to be redundant, since we're adding the font weight in the font shorthand line above.

2023-10-17 12:26 UTC, joshuabrileyatk reviewed
Looks good. One small change request.

2023-10-17 12:47 UTC, harry-atk requested changes
want to confirm the font shorthand works first

2023-10-18 21:01 UTC, oddwili commented
closing in favor of https://github.com/Americastestkitchen/mise-ui/pull/999

2023-10-18 21:01 UTC, closed without merging